/**
 * Where provisioned credentials go.
 *
 *   driver.apply() → Infisical (source of truth) → fan-out sinks
 *
 * Sinks are the places a running app actually reads from: the per-app `.env` files
 * used locally, Vercel project env for deploys, GitHub Actions secrets for CI, and
 * EAS env vars for mobile builds. Every sink is written from the same map, so the
 * four never drift from each other.
 *
 * The per-app `.env` split is what keeps two products isolated. Variable *names* stay
 * identical across products (`DATABASE_URL`, not `ACME_DATABASE_URL`), so nothing in
 * `packages/*` needs to know a product exists — each app just resolves its own file.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { exec, requireCommand } from "./exec";
import { requireJson } from "./http";
import { parseDotenv } from "./credentials";
import type { OutputSpec } from "./driver";
import { FactoryError, type Env, type Logger, type Surface } from "./types";

export const INFISICAL_HOST = "https://us.infisical.com";

/** Infisical folder per surface, so the api and mobile apps get disjoint secret sets. */
export const SURFACE_PATH: Record<Surface, string> = { api: "/api", mobile: "/mobile" };

/** Vercel calls them targets; the factory calls them environments. */
const VERCEL_TARGET: Record<Env, string> = {
  dev: "development",
  preview: "preview",
  prod: "production",
};

// ─── Infisical ────────────────────────────────────────────────────────────────

interface UniversalAuthLogin {
  readonly accessToken: string;
}

/**
 * Exchange a machine identity's client id + secret for a short-lived access token.
 * Universal Auth is platform-agnostic, so the same path works locally and in CI.
 */
export async function infisicalLogin(clientId: string, clientSecret: string): Promise<string> {
  const result = await requireJson<UniversalAuthLogin>(
    `${INFISICAL_HOST}/api/v1/auth/universal-auth/login`,
    {
      method: "POST",
      driver: "infisical",
      body: { clientId, clientSecret },
    },
  );
  return result.accessToken;
}

/**
 * Upsert one secret. Infisical distinguishes create from update, so this tries the
 * update path first and falls back to create — the ordering that makes re-running
 * `apply` against an already-provisioned product a no-op.
 */
export async function upsertSecret(
  token: string,
  args: {
    readonly projectId: string;
    readonly environment: Env;
    readonly path: string;
    readonly key: string;
    readonly value: string;
  },
): Promise<void> {
  const base = `${INFISICAL_HOST}/api/v3/secrets/raw/${encodeURIComponent(args.key)}`;
  const payload = {
    workspaceId: args.projectId,
    environment: args.environment,
    secretPath: args.path,
    secretValue: args.value,
  };
  const headers = { authorization: `Bearer ${token}` };

  const updated = await requireJsonOrUndefined(base, {
    method: "PATCH",
    driver: "infisical",
    headers,
    body: payload,
  });

  if (updated) return;

  await requireJson(base, { method: "POST", driver: "infisical", headers, body: payload });
}

async function requireJsonOrUndefined(url: string, options: Parameters<typeof requireJson>[1]) {
  try {
    await requireJson(url, options);
    return true;
  } catch (error) {
    // A missing secret is the expected first-run case, not a failure.
    if (error instanceof FactoryError && /→ 40[04]/.test(error.message)) return false;
    throw error;
  }
}

/** Push a whole map, routing each key to the folders its surfaces consume it from. */
export async function pushSecrets(
  token: string,
  args: {
    readonly projectId: string;
    readonly environment: Env;
    readonly secrets: Readonly<Record<string, string>>;
    readonly placement: ReadonlyMap<string, readonly Surface[]>;
    readonly logger: Logger;
  },
): Promise<number> {
  let written = 0;

  for (const [key, value] of Object.entries(args.secrets)) {
    // Unplaced keys default to both surfaces rather than being silently dropped.
    const surfaces = args.placement.get(key) ?? (["api", "mobile"] as const);
    for (const surface of surfaces) {
      await upsertSecret(token, {
        projectId: args.projectId,
        environment: args.environment,
        path: SURFACE_PATH[surface],
        key,
        value,
      });
      written++;
    }
    args.logger.debug(`infisical ← ${key} (${surfaces.join(", ")})`);
  }

  return written;
}

// ─── Local .env materialisation ───────────────────────────────────────────────

export function envFilePath(repoRoot: string, product: string, surface: Surface): string {
  return join(repoRoot, "apps", product, surface, ".env");
}

const HEADER = [
  "# Generated by `pnpm factory sync`. Do not edit by hand — edit in Infisical.",
  "# This file is gitignored. Secrets live in Infisical; state.json holds ids only.",
];

/**
 * Write a per-app `.env`.
 *
 * Any keys already in the file that the factory does not own are preserved, so a
 * hand-added local override (a LAN IP for `EXPO_PUBLIC_API_URL`, say) survives a sync.
 */
export async function writeEnvFile(
  path: string,
  secrets: Readonly<Record<string, string>>,
): Promise<{ written: number; preserved: number }> {
  let existing: Record<string, string> = {};
  try {
    existing = parseDotenv(await readFile(path, "utf8"));
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code !== "ENOENT") throw cause;
  }

  const preservedKeys = Object.keys(existing).filter((k) => !(k in secrets));
  const merged: Record<string, string> = {};
  for (const key of preservedKeys) merged[key] = existing[key] as string;
  Object.assign(merged, secrets);

  const lines = [
    ...HEADER,
    "",
    ...Object.keys(merged)
      .toSorted()
      .map((key) => `${key}=${quote(merged[key] as string)}`),
    "",
  ];

  await mkdir(join(path, ".."), { recursive: true });
  await writeFile(path, lines.join("\n"), "utf8");

  return { written: Object.keys(secrets).length, preserved: preservedKeys.length };
}

/** Quote only when the value could otherwise be misparsed. */
function quote(value: string): string {
  return /^[A-Za-z0-9_./:@+-]*$/.test(value) ? value : `"${value.replace(/(["\\])/g, "\\$1")}"`;
}

/** Split a secret map into per-surface maps using each driver's declared placement. */
export function splitBySurface(
  secrets: Readonly<Record<string, string>>,
  placement: ReadonlyMap<string, readonly Surface[]>,
): Record<Surface, Record<string, string>> {
  const out: Record<Surface, Record<string, string>> = { api: {}, mobile: {} };

  for (const [key, value] of Object.entries(secrets)) {
    for (const surface of placement.get(key) ?? (["api", "mobile"] as const)) {
      out[surface][key] = value;
    }
  }

  return out;
}

/** Build the key → surfaces map from every active driver's declared outputs. */
export function placementFrom(outputs: readonly OutputSpec[]): Map<string, readonly Surface[]> {
  return new Map(outputs.map((o) => [o.key, o.surfaces]));
}

// ─── Remote sinks ─────────────────────────────────────────────────────────────

/** Vercel project env. Upsert, so re-running does not 409 on an existing key. */
export async function pushToVercel(args: {
  readonly token: string;
  readonly teamId?: string;
  readonly projectId: string;
  readonly environment: Env;
  readonly secrets: Readonly<Record<string, string>>;
  readonly logger: Logger;
}): Promise<number> {
  const entries = Object.entries(args.secrets);
  if (entries.length === 0) return 0;

  await requireJson(`https://api.vercel.com/v10/projects/${args.projectId}/env`, {
    method: "POST",
    driver: "vercel",
    headers: { authorization: `Bearer ${args.token}` },
    query: { upsert: "true", teamId: args.teamId },
    body: entries.map(([key, value]) => ({
      key,
      value,
      // NEXT_PUBLIC_* must be plain: Vercel cannot inline an encrypted value at build.
      type: key.startsWith("NEXT_PUBLIC_") ? "plain" : "encrypted",
      target: [VERCEL_TARGET[args.environment]],
    })),
  });

  args.logger.debug(`vercel ← ${entries.length} env vars (${VERCEL_TARGET[args.environment]})`);
  return entries.length;
}

/** GitHub Actions secrets, via `gh` so libsodium encryption is handled for us. */
export async function pushToGitHub(args: {
  readonly repo: string;
  readonly secrets: Readonly<Record<string, string>>;
  readonly token: string;
  readonly logger: Logger;
}): Promise<number> {
  await requireCommand("gh", "github", "brew install gh");
  let count = 0;

  for (const [key, value] of Object.entries(args.secrets)) {
    await exec("gh", ["secret", "set", key, "--repo", args.repo, "--body", value], {
      driver: "github",
      env: { GH_TOKEN: args.token },
    });
    count++;
  }

  args.logger.debug(`github ← ${count} Actions secrets`);
  return count;
}

/**
 * EAS environment variables, so mobile builds are not shipped with empty
 * `EXPO_PUBLIC_*` values — the current `eas.json` has no `env` block at all.
 */
export async function pushToEas(args: {
  readonly projectDir: string;
  readonly environment: Env;
  readonly secrets: Readonly<Record<string, string>>;
  readonly token: string;
  readonly logger: Logger;
}): Promise<number> {
  await requireCommand("eas", "expo", "pnpm add -g eas-cli");
  const easEnv = args.environment === "dev" ? "development" : args.environment;
  let count = 0;

  for (const [key, value] of Object.entries(args.secrets)) {
    await exec(
      "eas",
      [
        "env:create",
        "--scope",
        "project",
        "--name",
        key,
        "--value",
        value,
        "--environment",
        easEnv,
        // EXPO_PUBLIC_* are embedded in the bundle, so they are not secret.
        "--visibility",
        key.startsWith("EXPO_PUBLIC_") ? "plaintext" : "sensitive",
        "--force",
        "--non-interactive",
      ],
      { cwd: args.projectDir, driver: "expo", env: { EXPO_TOKEN: args.token } },
    );
    count++;
  }

  args.logger.debug(`eas ← ${count} env vars (${easEnv})`);
  return count;
}

/** Pull Infisical → local `.env`, the read path behind `pnpm factory sync`. */
export async function pullToEnvFile(args: {
  readonly projectId: string;
  readonly environment: Env;
  readonly surface: Surface;
  readonly repoRoot: string;
  readonly product: string;
  readonly token: string;
  readonly logger: Logger;
}): Promise<string> {
  await requireCommand("infisical", "infisical", "brew install infisical/get-cli/infisical");
  const path = envFilePath(args.repoRoot, args.product, args.surface);
  await mkdir(join(path, ".."), { recursive: true });

  await exec(
    "infisical",
    [
      "export",
      "--projectId",
      args.projectId,
      "--env",
      args.environment,
      "--path",
      SURFACE_PATH[args.surface],
      "--format",
      "dotenv",
      "--output-file",
      path,
    ],
    { driver: "infisical", env: { INFISICAL_TOKEN: args.token } },
  );

  args.logger.debug(`${args.surface}/.env ← infisical ${SURFACE_PATH[args.surface]}`);
  return path;
}
