import { graphql } from "~/gql";

/**
 * Operations the app sends. `graphql()` is generated by `pnpm codegen` from
 * `@habitual/core`'s `schema.graphql`, so a document that does not match the schema
 * is a typecheck failure rather than a runtime one.
 */

export const HealthQuery = graphql(`
  query Health {
    health {
      ok
      service
    }
  }
`);

export const CreateHabitMutation = graphql(`
  mutation CreateHabit($input: CreateHabitInput!) {
    createHabit(input: $input) {
      id
      name
      color
      repeatDays
      reminderAt
      dailyGoal
      streak
      createdAt
    }
  }
`);
