/**
 * GitHub — the product's repository.
 *
 * Vercel links a project to a repo at creation time, so this must land first.
 */
import { request, requireJson } from "../http";
import type { Ctx, Driver } from "../driver";
import type { PlanStep, VerifyResult } from "../types";

const API = "https://api.github.com";

/** The org every product repo is created under. */
export const GITHUB_ORG = "malusi-solutions";

interface Repo {
  readonly full_name: string;
  readonly html_url: string;
  readonly default_branch: string;
}

function headers(ctx: Ctx): Record<string, string> {
  return {
    authorization: `Bearer ${ctx.credentials["GITHUB_TOKEN"]}`,
    "x-github-api-version": "2022-11-28",
  };
}

/** Repos are not per-environment — one repo serves dev, preview and prod. */
const repoName = (ctx: Ctx) => `${GITHUB_ORG}/${ctx.product}`;

async function findRepo(ctx: Ctx): Promise<Repo | undefined> {
  return request<Repo>(`${API}/repos/${repoName(ctx)}`, {
    driver: "github",
    headers: headers(ctx),
    allowStatus: [404],
  });
}

export const githubDriver: Driver = {
  id: "github",
  dependsOn: [],
  outputs: [],
  credentials: ["GITHUB_TOKEN"],

  resourceName: (ctx) => repoName(ctx),

  async plan(ctx): Promise<readonly PlanStep[]> {
    const existing = await findRepo(ctx);
    return [
      {
        action: existing ? "noop" : "create",
        resource: `GitHub repo ${repoName(ctx)}`,
        detail: existing ? "already exists" : "private, in the malusi-solutions org",
      },
    ];
  },

  async apply(ctx) {
    const existing = await findRepo(ctx);

    if (existing) {
      ctx.logger.debug(`repo ${existing.full_name} already exists`);
      return {
        statePatch: { repo: existing.full_name, defaultBranch: existing.default_branch },
      };
    }

    if (ctx.dryRun) return {};

    const created = await requireJson<Repo>(`${API}/orgs/${GITHUB_ORG}/repos`, {
      method: "POST",
      driver: "github",
      headers: headers(ctx),
      body: {
        name: ctx.product,
        description: `${ctx.manifest.displayName} — generated by the Malusi Solutions factory`,
        private: true,
        has_issues: true,
        has_wiki: false,
        has_projects: false,
        auto_init: true,
      },
    });

    ctx.logger.info(`  created ${created.html_url}`);
    return { statePatch: { repo: created.full_name, defaultBranch: created.default_branch } };
  },

  async verify(ctx): Promise<VerifyResult> {
    const existing = await findRepo(ctx);
    return existing
      ? { ok: true, message: `repo ${existing.full_name} reachable` }
      : { ok: false, message: `repo ${repoName(ctx)} not found` };
  },

  async destroy(ctx) {
    await request(`${API}/repos/${repoName(ctx)}`, {
      method: "DELETE",
      driver: "github",
      headers: headers(ctx),
      allowStatus: [404],
    });
    ctx.logger.info(`  deleted repo ${repoName(ctx)}`);
  },
};
