import { defineConfig } from "vite-plus";

export default defineConfig({
  run: {
    tasks: {
      // Reads ../core/schema.graphql (regenerated by core#codegen first) and
      // emits the typed client into src/gql/.
      codegen: {
        command: "graphql-codegen --config codegen.ts",
        dependsOn: [{ task: "codegen", from: "dependencies" }],
        // Explicit output so a cache hit restores the committed artifacts —
        // CI's codegen drift check diffs them, so they must always materialize.
        output: ["src/gql/**"],
      },
      build: {
        command: "expo export --platform ios --output-dir expo-export",
        dependsOn: ["codegen", { task: "build", from: "dependencies" }],
        // Cached tasks run with a filtered environment: only the vars below
        // (fingerprinted) plus vp's common set reach the task. EXPO_* vars are
        // not in vp's common set, so every var the app reads must be listed.
        env: [
          "NODE_ENV",
          "SKIP_ENV_VALIDATION",
          "EXPO_PUBLIC_API_URL",
          "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY",
          "EXPO_PUBLIC_POSTHOG_KEY",
          "EXPO_PUBLIC_POSTHOG_HOST",
          "EXPO_PUBLIC_SENTRY_DSN",
        ],
        output: ["expo-export/**"],
      },
      typecheck: {
        command: "tsc --noEmit",
        dependsOn: ["codegen"],
      },
    },
  },
});
